services:
  api-care:
    build: .
    ports:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://meu-postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSW- POSTGRES_USER=${DB_USER}ORD=${DB_PASSWORD}
    depends_on:
      - meu-postgres

  meu-postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - dados-do-banco:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  dados-do-banco:


